// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN0uTyXNdjnTFFpc4VxpgNKWEFOWb4-kA',
    appId: '1:726847533270:web:f9ced6002348d4519b1977',
    messagingSenderId: '726847533270',
    projectId: 'fooddeliveryapppranav',
    authDomain: 'fooddeliveryapppranav.firebaseapp.com',
    storageBucket: 'fooddeliveryapppranav.appspot.com',
    measurementId: 'G-65DGHHBLPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftcoBEue-M8hQfcB-M-7ZAbhm_5PVmck',
    appId: '1:726847533270:android:f8faab0dba68351c9b1977',
    messagingSenderId: '726847533270',
    projectId: 'fooddeliveryapppranav',
    storageBucket: 'fooddeliveryapppranav.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk41Jwtwi2u4R8WEHoVOsMRZb36howCtw',
    appId: '1:726847533270:ios:602b4d3bb695eb479b1977',
    messagingSenderId: '726847533270',
    projectId: 'fooddeliveryapppranav',
    storageBucket: 'fooddeliveryapppranav.appspot.com',
    iosBundleId: 'com.example.foodPanda',
  );
}
